---
title: Utopia
author: Your Name
date: '`r Sys.Date()`'
output:
  arsedown::pdf_memo:
    smolhead: true
    smolcaps: true
    keep_md: true
    keep_tex: true
    number_sections: false
    toc: false
    toc_depth: 2
    self_contained: false
fontfamily: fourier
fontsize: 11pt
geometry: top=0.55in, bottom=0.55in, left=0.65in, right=0.65in
subparagraph: true
linkcolor: blue
urlcolor: teal
bibliography: '`r system.file("include", "arsenoff.bib", package = "arsedown")`'
csl: '`r arsedown::space_csl()`'
knit: (function(input_file, encoding, ...) {rmarkdown::render(input_file, encoding=encoding,
  output_dir=getwd(), clean=FALSE)})
vignette: |-
  >
   %\VignetteIndexEntry{Utopia}
   %\VignetteEngine{knitr::rmarkdown}
   %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width       = 7,
  fig.height      = 4,
  fig.pos         = "!b",
  fig.align       = "center",
  dev             = "png",
  dpi             = 300,
  out.extra       = "",
  eval            = TRUE,
  echo            = FALSE,
  include         = FALSE,
  message         = FALSE,
  warning         = FALSE,
  error           = FALSE,
  progress        = FALSE,
  results         = "asis"
)
```

In the beginning was the Word, and the Word was with God, and the Word was God. He was in the beginning with God. All things came into being through him, and without him not one thing came into being. What has come into being in him was life, and the life was the light of all people.

The light shines in the darkness, and the darkness did not overcome it. There was a man sent from God, whose name was John. He came as a witness to testify to the light, so that all might believe through him. He himself was not the light, but he came to testify to the light. The true light, which enlightens everyone, was coming into the world. He was in the world, and the world came into being through him; yet the world did not know him. He came to what was his own, and his own people did not accept him. But to all who received him, who believed in his name, he gave power to become children of God, who were born, not of blood or of the will of the flesh or of the will of man, but of God. And the Word became flesh and lived among us, and we have seen his glory, the glory as of a father’s only son, full of grace and truth.

(John testified to him and cried out, “This was he of whom I said, ‘He who comes after me ranks ahead of me because he was before me.’”) From his fullness we have all received, grace upon grace. The law indeed was given through Moses; grace and truth came through Jesus Christ. No one has ever seen God. It is God the only Son, who is close to the Father’s heart, who has made him known. 
